/// Represents one specific date/time session of a curriculum activity.
///
/// An [Activity] can have many slots. Students pick one slot when booking
/// through the KoQ Booking page. The [attendanceCode] is generated by
/// Pusat Adab on the day of the event so students can mark attendance.
class ActivitySlot {
  const ActivitySlot({
    required this.id,
    required this.activityId,
    required this.date,
    required this.time,
    required this.capacity,
    required this.registered,
    this.attendanceCode,
  });

  /// Database primary key for this slot.
  final int id;

  /// Foreign key linking this slot to its parent [Activity].
  final int activityId;

  /// Date of the session in 'YYYY-MM-DD' format (e.g. '2025-06-15').
  final String date;

  /// Time of the session as a display string (e.g. '8:00 AM - 12:00 PM').
  final String time;

  /// Maximum number of students allowed in this slot.
  final int capacity;

  /// Number of students who have already registered for this slot.
  /// Stored as a denormalized count on the backend for performance.
  final int registered;

  /// 6-character attendance code generated by Pusat Adab when the event starts.
  /// Null until Pusat Adab activates it on the day of the event.
  final String? attendanceCode;

  // ── Computed properties ────────────────────────────────────────────────────

  /// Returns true if this slot still has at least one open seat.
  /// Used to filter out fully-booked slots in the booking dialog.
  bool get isAvailable => registered < capacity;

  // ── Factory constructor ────────────────────────────────────────────────────

  /// Deserializes an [ActivitySlot] from a JSON map.
  /// [registered] defaults to 0 if the backend omits it (e.g. in new slot responses).
  factory ActivitySlot.fromJson(Map<String, dynamic> json) {
    return ActivitySlot(
      id:             (json['id'] as num).toInt(),
      activityId:     (json['activity_id'] as num).toInt(),
      date:           json['date'] as String,
      time:           json['time'] as String,
      capacity:       (json['capacity'] as num).toInt(),
      registered:     (json['registered'] as num?)?.toInt() ?? 0,
      attendanceCode: json['attendance_code'] as String?,
    );
  }
}
